package org.lanqiao.entity;

public class Stu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sage
     *
     * @mbg.generated
     */
    private Integer sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.ssex
     *
     * @mbg.generated
     */
    private String ssex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.id
     *
     * @return the value of stu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.id
     *
     * @param id the value for stu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sname
     *
     * @return the value of stu.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sname
     *
     * @param sname the value for stu.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sage
     *
     * @return the value of stu.sage
     *
     * @mbg.generated
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sage
     *
     * @param sage the value for stu.sage
     *
     * @mbg.generated
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.ssex
     *
     * @return the value of stu.ssex
     *
     * @mbg.generated
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.ssex
     *
     * @param ssex the value for stu.ssex
     *
     * @mbg.generated
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    @Override
    public String toString() {
        return "Stu{" +
                "id=" + id +
                ", sname='" + sname + '\'' +
                ", sage=" + sage +
                ", ssex='" + ssex + '\'' +
                '}';
    }
}